// @generated by typebridge complex fixture. Do not edit.

export type JsonValue = unknown;

export type ConnectionStatus = "connected" | "idle" | "error" | "sshTunnelDown";

export type SqlDialect = "postgresql" | "mysql" | "sqlite" | "snowflake" | "oracle" | "sqlserver";

export type DbObjectKind = "table" | "view" | "materializedView" | "procedure" | "function" | "trigger" | "sequence" | "index";

export type Severity = "info" | "warning" | "error" | "fatal";

/** Redaction policy used before schema or sample rows are sent to an AI provider. */
export interface RedactionPolicy {
  mode: "none" | "safe" | "strict";
  sampleSize?: number | null;
  blockedColumns: string[];
}

/** Saved connection profile. Secrets are never exported into the generated API. */
export interface ConnectionProfile {
  id: string;
  displayName: string;
  dialect: SqlDialect;
  host: string;
  port?: number | null;
  database?: string | null;
  tags: Record<string, string>;
  ssh?: { host: string; user: string; port?: number | null; agentForwarding: boolean; } | null;
  tlsMode: "disable" | "prefer" | "require" | "verifyFull";
}

/** Live connection info shown in the workspace sidebar. */
export interface ConnectionInfo {
  id: string;
  profileId: string;
  status: ConnectionStatus;
  latencyMs?: number | null;
  proxy: "direct" | "ssh" | "cloud";
  warnings: Diagnostic[];
}

/** Schema browser object. */
export interface DbObject {
  name: string;
  schemaName?: string | null;
  kind: DbObjectKind;
  rowCount?: number | null;
  columns: ColumnMeta[];
  tags: Record<string, string>;
}

/** Column metadata used by completion and result grid rendering. */
export interface ColumnMeta {
  name: string;
  dataType: string;
  nullable: boolean;
  primaryKey: boolean;
  foreignKey?: { table: string; column: string; } | null;
  samples?: JsonValue[] | null;
}

export interface Diagnostic {
  severity: Severity;
  code: string;
  message: string;
  location?: { line: number; column: number; } | null;
}

/** Options for executing one or more SQL statements. */
export interface RunOptions {
  maxRows: number;
  timeoutMs?: number | null;
  explain: boolean;
  dryRun: boolean;
  variables: Record<string, JsonValue>;
  redaction: RedactionPolicy;
}

export interface QueryResult {
  columns: ColumnMeta[];
  rows: JsonValue[][];
  stats: { elapsedMs: number; scannedRows?: number | null; scannedBytes?: number | null; };
  diagnostics: Diagnostic[];
  truncated: boolean;
  message?: string | null;
}

export interface WorkspaceSnapshot {
  activeConnectionId?: string | null;
  connections: ConnectionInfo[];
  objectsByConnection: Record<string, DbObject[]>;
  recentQueries: { sql: string; dialect: SqlDialect; ranAt: string; durationMs: number; }[];
}

export function workspaceSnapshot(): Promise<WorkspaceSnapshot> {
  return request("workspace_snapshot");
}

/** Open a connection without exposing secrets to the frontend type surface. */
export function openConnection(profile: ConnectionProfile, redactionPolicy: RedactionPolicy): Promise<ConnectionInfo> {
  return request("open_connection", { profile, redactionPolicy });
}

/** Run a batch and return a single normalized result object. */
export function runSqlBatch(connectionId: string, statements: string[], options: RunOptions): Promise<QueryResult> {
  return request("run_sql_batch", { connectionId, statements, options });
}

export function searchCatalog(connectionId: string, query: string, limit: number): Promise<DbObject[]> {
  return request("search_catalog", { connectionId, query, limit });
}

export function exportExtensionPackage(extensionId: string, targetPath: string): Promise<void> {
  return request("export_extension_package", { extensionId, targetPath });
}

/**
 * Exhaustiveness guard for closed unions. Use in a `default` branch:
 *   default: return assertNever(x);
 * Adding a variant without handling it then becomes a compile error.
 */
export function assertNever(value: never): never {
  throw new Error("Unhandled union variant: " + JSON.stringify(value));
}
