//! The assembly layer — what typeship actually owns.
//!
//! Per-type renderers ([`ts-rs`], [`specta`], …) lower one type at a time. A
//! [`Bridge`] is the orchestrator above them: it collects declarations and command
//! wrappers, stamps a generated-file header, optionally emits the `assertNever`
//! exhaustiveness helper, and renders one deterministic, formatted file. The same
//! value can then [`Rendered::write`] it or [`Rendered::check`] it against the
//! committed copy in CI.
//!
//! [`ts-rs`]: https://github.com/Aleph-Alpha/ts-rs
//! [`specta`]: https://github.com/specta-rs/specta

mod defects;
mod rendered;

use crate::command::{Command, Transport};
use crate::ir::Decl;
use crate::ts::TsModule;

pub use defects::{Defect, DefectKind};
pub use rendered::Rendered;

/// The default header stamped onto generated files. Mirrors the convention the
/// irodori desktop app already uses for its `ts-rs` output, so a swap to
/// typeship is invisible to readers of the file.
const DEFAULT_HEADER: &str = "// @generated by typeship. Do not edit.";

/// The standard exhaustiveness guard. A `default:` branch that calls this fails to
/// type-check the moment a new union variant is added but left unhandled — the
/// TypeScript echo of PureScript/Elm totality.
const ASSERT_NEVER: &str = "\
/**
 * Exhaustiveness guard for closed unions. Use in a `default` branch:
 *   default: return assertNever(x);
 * Adding a variant without handling it then becomes a compile error.
 */
export function assertNever(value: never): never {
  throw new Error(\"Unhandled union variant: \" + JSON.stringify(value));
}
";

/// A builder that assembles declarations and commands into one TypeScript module.
#[derive(Clone, Debug)]
pub struct Bridge {
    transport: Transport,
    header: String,
    decls: Vec<Decl>,
    commands: Vec<Command>,
    emit_assert_never: bool,
}

impl Bridge {
    /// A bridge targeting a given transport, with the default header.
    pub fn new(transport: Transport) -> Self {
        Bridge {
            transport,
            header: DEFAULT_HEADER.to_string(),
            decls: Vec::new(),
            commands: Vec::new(),
            emit_assert_never: false,
        }
    }

    /// A bridge whose commands render as Tauri `invoke` wrappers.
    pub fn tauri() -> Self {
        Bridge::new(Transport::Tauri)
    }

    /// A bridge whose commands render as transport-agnostic `request` wrappers.
    pub fn fetch() -> Self {
        Bridge::new(Transport::Fetch)
    }

    /// Override the generated-file header (provide the comment text *without* a
    /// trailing newline; lines are emitted verbatim).
    pub fn header(mut self, header: impl Into<String>) -> Self {
        self.header = header.into();
        self
    }

    /// Add a declaration. Takes a reference and clones, so the same [`Decl`] can be
    /// reused across bridges (e.g. an app bridge and an extension-SDK bridge).
    pub fn decl(mut self, decl: &Decl) -> Self {
        self.decls.push(decl.clone());
        self
    }

    /// Add several declarations.
    pub fn decls<'a, I>(mut self, decls: I) -> Self
    where
        I: IntoIterator<Item = &'a Decl>,
    {
        self.decls.extend(decls.into_iter().cloned());
        self
    }

    /// Add a command wrapper.
    pub fn command(mut self, command: Command) -> Self {
        self.commands.push(command);
        self
    }

    /// Emit the `assertNever` exhaustiveness helper at the end of the module.
    pub fn with_assert_never(mut self, enabled: bool) -> Self {
        self.emit_assert_never = enabled;
        self
    }

    /// Scan for anything that would keep the rendered module from compiling —
    /// an identifier emitted twice (two declarations with one name, two commands
    /// lowering to one function, two fields or arguments colliding through the
    /// naming isomorphism), or a name that cannot bind at all. An empty result
    /// means the module is well-formed.
    ///
    /// Pure: no IO, no rendering. See [`Bridge::try_render`] for the checked
    /// render path.
    pub fn defects(&self) -> Vec<Defect> {
        defects::scan(&self.decls, &self.commands)
    }

    /// Render, or refuse with the defects that would make the output invalid
    /// TypeScript.
    ///
    /// Prefer this over [`Bridge::render`] anywhere the result is written to
    /// disk: a duplicate identifier is a `tsc` error in the *consumer's* build,
    /// which is exactly the class of failure this crate exists to move earlier.
    pub fn try_render(&self) -> Result<Rendered, Vec<Defect>> {
        let defects = self.defects();
        if defects.is_empty() {
            Ok(self.render())
        } else {
            Err(defects)
        }
    }

    /// Render the assembled module into a [`Rendered`] value, without checking
    /// that it compiles — see [`Bridge::try_render`] for the checked variant.
    pub fn render(&self) -> Rendered {
        let mut module = TsModule::new();
        module.push(self.header.clone());

        if !self.commands.is_empty() {
            if let Some(import) = self.transport.import_line() {
                module.push(import);
            }
        }

        for decl in &self.decls {
            module.push_rendered(decl.render());
        }

        for command in &self.commands {
            module.push_rendered(command.render(self.transport));
        }

        if self.emit_assert_never {
            module.push_rendered(ASSERT_NEVER);
        }

        let contents = module.finish();
        Rendered { contents }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::command::Arg;
    use crate::ir::TsType;

    #[test]
    fn doc_example_renders_alias_and_command() {
        let status = Decl::alias(
            "ConnectionStatus",
            TsType::string_literals(["connected", "idle"]),
        );
        let ts = Bridge::tauri()
            .decl(&status)
            .command(Command::new("workspace_snapshot", "WorkspaceSnapshot"))
            .render();

        assert!(
            ts.contents
                .contains("export type ConnectionStatus = \"connected\" | \"idle\";"),
            "{}",
            ts.contents
        );
        assert!(
            ts.contents
                .contains("export function workspaceSnapshot(): Promise<WorkspaceSnapshot>"),
            "{}",
            ts.contents
        );
        // Header is present and the Tauri import is pulled in because there is a command.
        assert!(ts
            .contents
            .starts_with("// @generated by typeship. Do not edit."));
        assert!(ts
            .contents
            .contains("import { invoke } from \"@tauri-apps/api/core\";"));
        // Exactly one trailing newline.
        assert!(ts.contents.ends_with("}\n"));
        assert!(!ts.contents.ends_with("\n\n"));
    }

    #[test]
    fn no_import_without_commands() {
        let status = Decl::alias("Status", TsType::string_literals(["a"]));
        let ts = Bridge::tauri().decl(&status).render();
        assert!(!ts.contents.contains("import"), "{}", ts.contents);
    }

    #[test]
    fn assert_never_is_opt_in() {
        let off = Bridge::tauri().render();
        assert!(!off.contents.contains("assertNever"));
        let on = Bridge::tauri().with_assert_never(true).render();
        assert!(on
            .contents
            .contains("export function assertNever(value: never): never"));
    }

    #[test]
    fn render_is_deterministic() {
        let build = || {
            Bridge::tauri()
                .decl(&Decl::interface(
                    "Q",
                    [crate::ir::Field::rust("connection_id", TsType::string())],
                ))
                .command(
                    Command::new("run_query", "QueryResult")
                        .arg(Arg::rust("connection_id", TsType::string())),
                )
                .render()
        };
        assert_eq!(build(), build());
    }
}
